Update build-ffmpeg-aarch64.yml

diff --git a/.github/workflows/build-ffmpeg-aarch64.yml b/.github/workflows/build-ffmpeg-aarch64.yml
--- a/.github/workflows/build-ffmpeg-aarch64.yml
+++ b/.github/workflows/build-ffmpeg-aarch64.yml
@@ -33,14 +33,8 @@ jobs:
     - name: Modify configure script for OpenGL ES
       run: |
         cd $GITHUB_WORKSPACE/ffmpeg-7.0.1
-        sed -i 's/enabled opengl            && { check_lib opengl GL\/glx\.h glXGetProcAddress "-lGL" ||\
-                               check_lib opengl windows\.h wglGetProcAddress "-lopengl32 -lgdi32" ||\
-                               check_lib opengl OpenGL\/gl3\.h glGetError "-Wl,-framework,OpenGL" ||\
-                               check_lib opengl ES2\/gl\.h glGetError "-isysroot=${sysroot} -Wl,-framework,OpenGLES" ||\
-                               die "ERROR: opengl not found\." \
-                             }/enabled opengl && { check_lib opengl "GLES2\/gl2\.h" glGetError "-lGLESv2" ||\
-                                    die "ERROR: opengl not found\." \
-                                  }/' configure
+        sed -i '7048,7053d' configure
+        sed -i '7047a enabled opengl            && { check_lib opengl "GLES2/gl2.h" glGetError "-lGLESv2" || die "ERROR: opengl not found."; }' configure
     
     - name: Print FFmpeg configure script content
       run: |
