Update build-ffmpeg-aarch64.yml

diff --git a/.github/workflows/build-ffmpeg-aarch64.yml b/.github/workflows/build-ffmpeg-aarch64.yml
--- a/.github/workflows/build-ffmpeg-aarch64.yml
+++ b/.github/workflows/build-ffmpeg-aarch64.yml
@@ -70,6 +70,11 @@ jobs:
           ln -s /usr/bin/pkg-config $TOOLCHAIN/bin/aarch64-linux-android-pkg-config
         fi
     
+    - name: Check for pkg-config and llvm-nm
+      run: |
+          find $NDK -name llvm-ar -print -quit || echo "llvm-ar not found"
+          find $NDK -name llvm-nm -print -quit || echo "llvm-nm not found"
+    
     - name: Configure FFmpeg for arm64-v8a
       run: |
         cd $GITHUB_WORKSPACE/ffmpeg-6.1.1
