Update build-ffmpeg.yml

diff --git a/.github/workflows/build-ffmpeg.yml b/.github/workflows/build-ffmpeg.yml
--- a/.github/workflows/build-ffmpeg.yml
+++ b/.github/workflows/build-ffmpeg.yml
@@ -39,15 +39,14 @@ jobs:
       run: |
         # 重新设置 ANDROID_NDK_HOME 环境变量
         export ANDROID_NDK_HOME=$PWD/android-ndk-r26d 
-        # 进入NDK目录
+        # 进入 NDK 目录
         cd $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr
-        pwd  # 打印当前工作目录
 
-        # 尝试使用不同的 -p 选项来应用补丁, 并添加 -N 参数
+        # 应用补丁，注意 -p 参数
         for patch in $GITHUB_WORKSPACE/ndk-26b/*.patch; do
-          if ! patch -N -p1 < $patch; then 
-            echo "Failed to apply patch with -p1, trying with -p0"
-            patch -N -p0 < $patch 
+          if ! patch -N -p4 < $patch; then 
+            echo "Failed to apply patch with -p4, trying with -p5"
+            patch -N -p5 < $patch  
           fi
         done
 
