Update build-ffmpeg-aarch64.yml

diff --git a/.github/workflows/build-ffmpeg-aarch64.yml b/.github/workflows/build-ffmpeg-aarch64.yml
--- a/.github/workflows/build-ffmpeg-aarch64.yml
+++ b/.github/workflows/build-ffmpeg-aarch64.yml
@@ -32,8 +32,8 @@ jobs:
     
     - name: Modify configure script for OpenGL ES
       run: |
-        cd $GITHUB_WORKSPACE/ffmpeg-7.0.1
-        sed -i '7048,7053d;7047a enabled opengl            && { check_lib opengl "GLES2/gl2.h" glGetError "-lGLESv2" || die "ERROR: opengl not found."; }' configure
+        sed -i '/enabled opengl            && { check_lib opengl GL\/glx.h glXGetProcAddress "-lGL" ||/,/die "ERROR: opengl not found."/c\
+        enabled opengl            && { check_lib opengl "GLES2/gl2.h" glGetError "-lGLESv2" || die "ERROR: opengl not found."; }' configure
     
     - name: Print FFmpeg configure script content
       run: |
