Update build-ffmpeg-aarch64.yml

diff --git a/.github/workflows/build-ffmpeg-aarch64.yml b/.github/workflows/build-ffmpeg-aarch64.yml
--- a/.github/workflows/build-ffmpeg-aarch64.yml
+++ b/.github/workflows/build-ffmpeg-aarch64.yml
@@ -26,13 +26,6 @@ jobs:
         wget -O - https://www.ffmpeg.org/releases/ffmpeg-7.0.1.tar.xz | tar -xJv -C $GITHUB_WORKSPACE
 
     
-    - name: Configure FFmpeg for Android with OpenGL
-      run: |
-        cd $GITHUB_WORKSPACE/ffmpeg-7.0.1
-        sed -i '/check_lib opengl GL\/gl.h glXGetProcAddress "-lGL" ||/a\
-        check_lib opengl GLES2\/gl2.h glGetError "-lGLESv2" || \\\n\
-        check_lib opengl GLES3\/gl3.h glGetError "-lGLESv3" ||' configure
-    
     - name: Show context around target lines in Makefile and allfilters.c
       if: false
       run: |
@@ -47,10 +40,9 @@ jobs:
         
     
     - name: Modify configure script for OpenGL ES
-      if: false
       run: |
         cd $GITHUB_WORKSPACE/ffmpeg-7.0.1
-        sed -i '/enabled opengl            && { check_lib opengl GL\/glx.h glXGetProcAddress "-lGL" ||/,/^                             }/c\enabled opengl            && { check_lib opengl "GLES2\/gl2.h" glGetError "-lGLESv2" || die "ERROR: opengl not found."; }' configure
+        sed -i '/enabled opengl            && { check_lib opengl GL\/glx.h glXGetProcAddress "-lGL" ||/,/^                             }/c\enabled opengl            && { check_lib opengl "GLES2\/gl2.h" glGetError "-lGLESv2" || check_lib opengl "EGL/egl.h" eglGetDisplay "-lEGL" || die "ERROR: opengl not found."; }' configure
     
     - name: Print FFmpeg configure script content
       run: |
