Update build-ffmpeg.yml

diff --git a/.github/workflows/build-ffmpeg.yml b/.github/workflows/build-ffmpeg.yml
--- a/.github/workflows/build-ffmpeg.yml
+++ b/.github/workflows/build-ffmpeg.yml
@@ -85,31 +85,54 @@ jobs:
         echo "_FFMPEG_SOVER_avcodec=60" >> $GITHUB_ENV
         echo "_FFMPEG_SOVER_avformat=60" >> $GITHUB_ENV
 
-    - name: Set permissions for FFmpeg source
-      run: chmod -R 777 $GITHUB_WORKSPACE/ffmpeg-6.1.1
-    
-    - name: Run build script
+    # FFmpeg 配置步骤，包含脚本内容
+    - name: Configure FFmpeg
       run: |
-        chmod +x build.sh
-        ./build.sh
+        cd $GITHUB_WORKSPACE/ffmpeg-6.1.1
 
-    - name: Print environment information
-      run: |
-        echo "Current working directory: $(pwd)"
-        echo "Environment variables:"
-        env | sort
-        echo "Configure debug information:"
-        cat $GITHUB_WORKSPACE/ffmpeg-6.1.1/configure_debug.txt  # 打印调试信息
+        local _EXTRA_CONFIGURE_FLAGS=""
+        if [ $ARCH = "arm" ]; then
+            _ARCH="armeabi-v7a"
+            _EXTRA_CONFIGURE_FLAGS="--enable-neon"
+        elif [ $ARCH = "i686" ]; then
+            _ARCH="x86"
+            _EXTRA_CONFIGURE_FLAGS="--disable-asm"
+        elif [ $ARCH = "x86_64" ]; then
+            _ARCH="x86_64"
+        elif [ $ARCH = "aarch64" ]; then
+            _ARCH=$ARCH
+            _EXTRA_CONFIGURE_FLAGS="--enable-neon"
+        else
+            echo "Unsupported arch: $ARCH"
+            exit 1
+        fi
 
-    - name: Set permissions for FFmpeg source
-      run: chmod -R 777 $GITHUB_WORKSPACE/ffmpeg-6.1.1
+        $GITHUB_WORKSPACE/ffmpeg-6.1.1/configure \
+            --arch="${_ARCH}" \
+            --as="$AS" \
+            --cc="$CC" \
+            --cxx="$CXX" \
+            --nm="$NM" \
+            --pkg-config="$PKG_CONFIG" \
+            --strip="$STRIP" \
+            --cross-prefix="${CROSS_PREFIX}" \
+            --disable-static \
+            --disable-symver \
+            --enable-shared \
+            --enable-cross-compile \
+            --enable-libx264 \
+            --prefix="${PREFIX}" \
+            --target-os=android \
+            $_EXTRA_CONFIGURE_FLAGS 
+
+        if [ $? -ne 0 ]; then
+            echo "Error: configure failed!"
+            exit 1
+        fi
 
     - name: Build FFmpeg
       run: |
         cd $GITHUB_WORKSPACE/ffmpeg-6.1.1
-        pwd  # 打印当前工作目录
-        ls -la tests  # 列出 tests 目录内容
-        export MAKEFLAGS=-I$GITHUB_WORKSPACE/ffmpeg-6.1.1/tests
         make -j$(nproc)
         make install
     
@@ -137,6 +160,3 @@ jobs:
       with:
         name: ffmpeg-shared-libraries
         path: ${PREFIX}/lib/libavutil.so
-                         
-          
-        
