Update build-ffmpeg-aarch64.yml

diff --git a/.github/workflows/build-ffmpeg-aarch64.yml b/.github/workflows/build-ffmpeg-aarch64.yml
--- a/.github/workflows/build-ffmpeg-aarch64.yml
+++ b/.github/workflows/build-ffmpeg-aarch64.yml
@@ -24,7 +24,7 @@ jobs:
         wget -O - https://www.ffmpeg.org/releases/ffmpeg-6.1.1.tar.xz | tar -xJv -C $GITHUB_WORKSPACE
 
     - name: Check for libswscale.version
-      run: ls -l $GITHUB_WORKSPACE/ffmpeg-6.1.1/libswscale/libswscale.version || echo "libswscale/libswscale.version not found"
+      run: ls -l $GITHUB_WORKSPACE/ffmpeg-6.1.1/libswscale || echo "libswscale not found"
     
     - name: Set up JDK 11
       uses: actions/setup-java@v2
