Update build-ffmpeg.yml

diff --git a/.github/workflows/build-ffmpeg.yml b/.github/workflows/build-ffmpeg.yml
--- a/.github/workflows/build-ffmpeg.yml
+++ b/.github/workflows/build-ffmpeg.yml
@@ -25,6 +25,14 @@ jobs:
     - name: Download FFmpeg source
       run: |
         wget -O - https://www.ffmpeg.org/releases/ffmpeg-6.1.1.tar.xz | tar -xJv -C $GITHUB_WORKSPACE
+
+    - name: Verify extracted files
+      run: |
+        ls -la $GITHUB_WORKSPACE/ffmpeg-6.1.1 
+        if [ ! -d "$GITHUB_WORKSPACE/ffmpeg-6.1.1/tests" ]; then
+          echo "Error: 'tests' directory not found!"
+          exit 1
+        fi
     
     - name: Set up JDK 11
       uses: actions/setup-java@v2
